USE db24;

DELIMITER $$
CREATE TRIGGER MyTBL_10A_guard1 BEFORE INSERT ON MyTBL_10A
FOR EACH ROW
BEGIN
DECLARE a varchar(100);
SELECT CURRENT_USER() INTO @a;
SIGNAL SQLSTATE '50000' SET message_text=@a;
END;$$
DELIMITER ;

INSERT INTO MyTBL_10A (Title) VALUE ('AAA');
